#!/bin/bash
cp web/*.html /web/cpnbook/public_html/.
cp web/*.css /web/cpnbook/public_html/.
cp web/*.jpg /web/cpnbook/public_html/.
cp web/*.pdf /web/cpnbook/public_html/.
cp web/projects/*.html /web/cpnbook/public_html/projects/.
cp --preserve=timestamps web/models/chapter2/*.cpn /web/cpnbook/public_html/models/chapter2/.
cp --preserve=timestamps web/models/chapter3/*.cpn /web/cpnbook/public_html/models/chapter3/.
cp --preserve=timestamps web/models/chapter5/*.cpn /web/cpnbook/public_html/models/chapter5/.
cp --preserve=timestamps web/models/chapter7/*.cpn /web/cpnbook/public_html/models/chapter7/.
cp --preserve=timestamps web/models/chapter10/*.cpn /web/cpnbook/public_html/models/chapter10/.
cp --preserve=timestamps web/models/chapter12/*.cpn /web/cpnbook/public_html/models/chapter12/.
cp --preserve=timestamps web/slides/CPN*.ppt /web/cpnbook/public_html/slides/.
cd /web/cpnbook/public_html/models
zip cpnbookmodels.zip chapter*/*.cpn
cd
cd /web/cpnbook/public_html/slides
zip cpnbookslides.zip *.ppt
